name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Runs a set of commands using the runners shell
    - name: Create and start an emulator
      run: |
          set -ex
          $ANDROID_HOME/tools/bin/sdkmanager --install 'build-tools;30.0.0' platform-tools 'platforms;android-29' > /dev/null
          $ANDROID_HOME/tools/bin/sdkmanager --install emulator > /dev/null
          echo y |$ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;default;x86_64' > /dev/null
          echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test --abi 'default/x86_64' --package 'system-images;android-29;default;x86_64' --sdcard 512M
          $ANDROID_HOME/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &
          sleep 60
         
    - name: Unlock the Lock Screen
      run: | 
          $ANDROID_HOME/platform-tools/adb shell input keyevent 82 &
          $ANDROID_HOME/platform-tools/adb shell input keyevent 4 &
      
    - name: Run screenshot tests
      run: ./gradlew executeScreenshotTests -Precord
